[package]
name = "pwm"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
text_io = "0.1.12"
clap = { version = "4.5.4", features = ["derive"] }
